const Images = {
  Logo: require('./Logo/Logo.png'),
  Zenylog: require('./Zenylog/Zenylog.png'),
  Profile: require('./Profile/Profile.png'),
  ManageLocation: require('./ManageLocation/ManageLocation.png'),
  ManageEmployee: require('./ManageEmployee/ManageEmployee.png'),
  ConsolidatedEmployeeSheet: require('./ConsolidatedEmployeeSheet/ConsolidatedEmployeeSheet.png'),
  ConsolidatedTimeSheet: require('./ConsolidatedTimeSheet/ConsolidatedTimeSheet.png'),
  Facebook: require('./Facebook/Facebook.png'),
  Eye: require('./Eye/Eye.png'),
  CheckActive: require('./CheckActive/CheckActive.png'),
  CheckDefault: require('./CheckDefault/CheckDefault.png'),
  Calender: require('./Calender/Calender.png'),
  DownArrow: require('./DownArrow/DownArrow.png'),
  Delete: require('./Delete/Delete.png'),
  Gallery: require('./Gallery/Gallery.png'),
  Google: require('./Google/Google.png'),
  Edit: require('./Edit/Edit.png'),
  Twitter: require('./Twitter/Twitter.png'),
  Landing: require('./Landing/Landing.png'),
  ProfilePhoto: require('./ProfilePhoto/ProfilePhoto.png'),
  Home: require('./Home/Home.png'),
  Log: require('./Log/Log.png'),
  Admin: require('./Admin/Admin.png'),
  Country: require('./Country/Country.png'),
  TickActive: require('./TickActive/TickActive.png'),
  TickDefault: require('./TickDefault/TickDefault.png'),
  ProfilePlaceHolder: require('./ProfilePlaceHolder/ProfilePlaceHolder.png'),
  ArrowBack: require('./ArrowBack/ArrowBack.png'),
  MyAccount: require('./MyAccount/MyAccount.png'),
  MyConsolidatedLog: require('./MyConsolidatedLog/MyConsolidatedLog.png'),
  MyTimeSheet: require('./MyTimeSheet/MyTimeSheet.png'),
  Search: require('./Search/Search.png'),
  Cancel: require('./Cancel/Cancel.png'),
  Call: require('./Call/Call.png'),
  EmployeeDelete: require('./EmployeeDelete/EmployeeDelete.png'),
  ScreenLogo: require('./ScreenLogo/ScreenLogo.png'),
  LogoSmall: require('./LogoSmall/LogoSmall.png'),
};

export default Images;
