
export const CREATE_BROADCAST_MESSAGE = "CREATE_BROADCAST_MESSAGE";
export const CREATE_BROADCAST_MESSAGE_SUCCESS = "CREATE_BROADCAST_MESSAGE_SUCCESS";
export const CREATE_BROADCAST_MESSAGE_FAILURE = "CREATE_BROADCAST_MESSAGE_FAILURE";


export const FETCH_BROADCAST_MESSAGE = "FETCH_BROADCAST_MESSAGE";
export const FETCH_BROADCAST_MESSAGE_SUCCESS = "FETCH_BROADCAST_MESSAGE_SUCCESS";
export const FETCH_BROADCAST_MESSAGE_FAILURE = "FETCH_BROADCAST_MESSAGE_FAILURE";