export const POST_ADD_WEEKLY_SHIFT = "POST_ADD_WEEKLY_SHIFT";
export const POST_ADD_WEEKLY_SHIFT_SUCCESS = "POST_ADD_WEEKLY_SHIFT_SUCCESS";
export const POST_ADD_WEEKLY_SHIFT_FAILURE = "POST_ADD_WEEKLY_SHIFT_FAILURE";