export const POST_ADD_WEEKLY_SHIFT = "POST_ADD_WEEKLY_SHIFT";
export const POST_ADD_WEEKLY_SHIFT_SUCCESS = "POST_ADD_WEEKLY_SHIFT_SUCCESS";
export const POST_ADD_WEEKLY_SHIFT_FAILURE = "POST_ADD_WEEKLY_SHIFT_FAILURE";

export const FETCH_BRANCH_SHIFTS = "FETCH_BRANCH_SHIFTS";
export const FETCH_BRANCH_SHIFTS_SUCCESS = "FETCH_BRANCH_SHIFTS_SUCCESS";
export const FETCH_BRANCH_SHIFTS_FAILURE = "FETCH_BRANCH_SHIFTS_FAILURE";

export const FETCH_BRANCH_WEEKLY_SHIFTS = "FETCH_BRANCH_WEEKLY_SHIFTS";
export const FETCH_BRANCH_WEEKLY_SHIFTS_SUCCESS = "FETCH_BRANCH_WEEKLY_SHIFTS_SUCCESS";
export const FETCH_BRANCH_WEEKLY_SHIFTS_FAILURE = "FETCH_BRANCH_WEEKLY_SHIFTS_FAILURE";

export const SELECTED_BRANCH_SHIFT_GROUP_NAME = "SELECTED_BRANCH_SHIFT_GROUP_NAME"

export const POST_ADD_SHIFT = "POST_ADD_SHIFT";
export const POST_ADD_SHIFT_SUCCESS = "POST_ADD_SHIFT_SUCCESS";
export const POST_ADD_SHIFT_FAILURE = "POST_ADD_SHIFT_FAILURE";