

export const URL_DELETE_USER = "URL_DELETE_USER";
export const URL_DELETE_USER_SUCCESS = "URL_DELETE_USER_SUCCESS";
export const URL_DELETE_USER_FAIL = "URL_DELETE_USER_FAIL";

export const EDIT_PROFILE_PICTURE = "EDIT_PROFILE_PICTURE";
export const EDIT_PROFILE_PICTURE_SUCCESS = "EDIT_PROFILE_PICTURE_USER_SUCCESS";
export const EDIT_PROFILE_PICTURE_FAIL = "EDIT_PROFILE_PICTURE_FAIL";

export const FETCH_DESIGNATION = "FETCH_DESIGNATION";
export const FETCH_DESIGNATION_SUCCESS = "FETCH_DESIGNATION_SUCCESS";
export const FETCH_DESIGNATION_FAILURE = "FETCH_DESIGNATION_FAILURE";

export const FETCH_DEPARTMENT = "FETCH_DEPARTMENT";
export const FETCH_DEPARTMENT_SUCCESS = "FETCH_DEPARTMENT_SUCCESS";
export const FETCH_DEPARTMENT_FAILURE = "FETCH_DEPARTMENT_FAILURE";

export const FETCH_ALL_BRANCHES_LIST = "FETCH_ALL_BRANCHES_LIST";
export const FETCH_ALL_BRANCHES_LIST_SUCCESS = "FETCH_ALL_BRANCHES_LIST_SUCCESS";
export const FETCH_ALL_BRANCHES_LIST_FAILURE = "FETCH_ALL_BRANCHES_LIST_FAILURE";

export const FETCH_EMPLOYEE_DETAILS = "FETCH_EMPLOYEE_DETAILS";
export const FETCH_EMPLOYEE_DETAILS_SUCCESS = "FETCH_EMPLOYEE_DETAILS_SUCCESS";
export const FETCH_EMPLOYEE_DETAILS_FAILURE = "FETCH_EMPLOYEE_DETAILS_FAILURE";

export const FETCH_EMPLOYEE_LIST = "FETCH_EMPLOYEE_LIST";
export const FETCH_EMPLOYEE_LIST_SUCCESS = "FETCH_EMPLOYEE_LIST_SUCCESS";
export const FETCH_EMPLOYEE_LIST_FAILURE = "FETCH_EMPLOYEE_LIST_FAILURE";

export const POST_EMPLOYEE_ADDITION = "POST_EMPLOYEE_ADDITION";
export const POST_EMPLOYEE_ADDITION_SUCCESS = "POST_EMPLOYEE_ADDITION_SUCCESS";
export const POST_EMPLOYEE_ADDITION_FAILURE = "POST_EMPLOYEE_ADDITION_FAILURE";


export const EDIT_EMPLOYEE="EDIT_EMPLOYEE"


export const FETCH_EMPLOYEE_TIME_SHEETS = "FETCH_EMPLOYEE_TIME_SHEETS";
export const FETCH_EMPLOYEE_TIME_SHEETS_SUCCESS = "FETCH_EMPLOYEE_TIME_SHEETS_SUCCESS";
export const FETCH_EMPLOYEE_TIME_SHEETS_FAILURE = "FETCH_EMPLOYEE_TIME_SHEETS_FAILURE";


export const FETCH_EMPLOYEE_CHECK_IN_LOGS = "FETCH_EMPLOYEE_CHECK_IN_LOGS";
export const FETCH_EMPLOYEE_CHECK_IN_LOGS_SUCCESS = "FETCH_EMPLOYEE_CHECK_IN_LOGS_SUCCESS";
export const FETCH_EMPLOYEE_CHECK_IN_LOGS_FAILURE = "FETCH_EMPLOYEE_CHECK_IN_LOGS_FAILURE";



export const FETCH_CHECK_IN_DETAILED_LOG_PER_DAY = "FETCH_CHECK_IN_DETAILED_LOG_PER_DAY";
export const FETCH_CHECK_IN_DETAILED_LOG_PER_DAY_SUCCESS = "FETCH_CHECK_IN_DETAILED_LOG_PER_DAY_SUCCESS";
export const FETCH_CHECK_IN_DETAILED_LOG_PER_DAY_FAILURE = "FETCH_CHECK_IN_DETAILED_LOG_PER_DAY_FAILURE";


export const FETCH_EMPLOYEE_EACH_USER_TIME_SHEETS = "FETCH_EMPLOYEE_EACH_USER_TIME_SHEETS";
export const FETCH_EMPLOYEE_EACH_USER_TIME_SHEETS_SUCCESS = "FETCH_EMPLOYEE_EACH_USER_TIME_SHEETS_SUCCESS";
export const FETCH_EMPLOYEE_EACH_USER_TIME_SHEETS_FAILURE = "FETCH_EMPLOYEE_EACH_USER_TIME_SHEETS_FAILURE";

export const ADD_DEPARTMENT = "ADD_DEPARTMENT";
export const ADD_DEPARTMENT_SUCCESS = "ADD_DEPARTMENT_SUCCESS";
export const ADD_DEPARTMENT_FAILURE = "ADD_DEPARTMENT_FAILURE";

export const ADD_DESIGNATION = "ADD_DESIGNATION";
export const ADD_DESIGNATION_SUCCESS = "ADD_DESIGNATION_SUCCESS";
export const ADD_DESIGNATION_FAILURE = "ADD_DESIGNATION_FAILURE";

export const ADD_FENCE_ADMIN = "ADD_FENCE_ADMIN";
export const ADD_FENCE_ADMIN_SUCCESS = "ADD_FENCE_ADMIN_SUCCESS";
export const ADD_FENCE_ADMIN_FAILURE = "ADD_FENCE_ADMIN_FAILURE";


export const FETCH_EMPLOYEE_ATTENDANCE_STATS = "FETCH_EMPLOYEE_ATTENDANCE_STATS";
export const FETCH_EMPLOYEE_ATTENDANCE_STATS_SUCCESS = "FETCH_EMPLOYEE_ATTENDANCE_STATS_SUCCESS";
export const FETCH_EMPLOYEE_ATTENDANCE_STATS_FAILURE = "FETCH_EMPLOYEE_ATTENDANCE_STATS_FAILURE";

export const FETCH_EMPLOYEE_TODAY_STATUS = "FETCH_EMPLOYEE_TODAY_STATUS";
export const FETCH_EMPLOYEE_TODAY_STATUS_SUCCESS = "FETCH_EMPLOYEE_TODAY_STATUS_SUCCESS";
export const FETCH_EMPLOYEE_TODAY_STATUS_FAILURE = "FETCH_EMPLOYEE_TODAY_STATUS_FAILURE";

export const FETCH_CHECK_IN_DETAILED_LOG = "FETCH_CHECK_IN_DETAILED_LOG";
export const FETCH_CHECK_IN_DETAILED_LOG_SUCCESS = "FETCH_CHECK_IN_DETAILED_LOG_SUCCESS";
export const FETCH_CHECK_IN_DETAILED_LOG_FAILURE = "FETCH_CHECK_IN_DETAILED_LOG_FAILURE";