export const VALIDATE_USER = "VALIDATE_USER";
export const VALIDATE_USER_SUCCESS = "VALIDATE_USER_SUCCESS";
export const VALIDATE_USER_FAIL = "VALIDATE_USER_FAIL";

export const VALIDATE_COMPANY_DETAILS = "VALIDATE_COMPANY_DETAILS";
export const VALIDATE_COMPANY_DETAILS_SUCCESS = "VALIDATE_COMPANY_DETAILS_SUCCESS";
export const VALIDATE_COMPANY_DETAILS_FAILURE = "VALIDATE_COMPANY_DETAILS_FAILURE";

export const REGISTER_ADMIN = "REGISTER_ADMIN";
export const REGISTER_ADMIN_SUCCESS = "REGISTER_ADMIN_SUCCESS";
export const REGISTER_ADMIN_FAILURE = "REGISTER_ADMIN_FAILURE";

export const UPLOAD_COMPANY_DOCUMENT = "UPLOAD_COMPANY_DOCUMENT";
export const UPLOAD_COMPANY_DOCUMENT_SUCCESS = "UPLOAD_COMPANY_DOCUMENT_SUCCESS";
export const UPLOAD_COMPANY_DOCUMENT_FAILURE = "UPLOAD_COMPANY_DOCUMENT_FAILURE";

export const OTP_LOGIN = "OTP_LOGIN";
export const OTP_LOGIN_SUCCESS = "OTP_LOGIN_SUCCESS";
export const OTP_LOGIN_FAILURE = "OTP_LOGIN_FAILURE";

export const RESEND_LOGIN_OTP = "RESEND_LOGIN_OTP";
export const RESEND_LOGIN_OTP_SUCCESS = "RESEND_LOGIN_OTP_SUCCESS";
export const RESEND_LOGIN_OTP_FAILURE = "RESEND_LOGIN_OTP_FAILURE";

export const ADMIN_VERIFICATION_OTP = "ADMIN_VERIFICATION_OTP";
export const ADMIN_VERIFICATION_OTP_SUCCESS = "ADMIN_VERIFICATION_OTP_SUCCESS";
export const ADMIN_VERIFICATION_OTP_FAILURE = "ADMIN_VERIFICATION_OTP_FAILURE";

export const NATURE_OF_BUSINESS = "NATURE_OF_BUSINESS";
export const NATURE_OF_BUSINESS_SUCCESS = "NATURE_OF_BUSINESS_SUCCESS";
export const NATURE_OF_BUSINESS_FAILURE = "NATURE_OF_BUSINESS_FAILURE";

export const TYPE_OF_BUSINESS = "TYPE_OF_BUSINESS";
export const TYPE_OF_BUSINESS_SUCCESS = "TYPE_OF_BUSINESS_SUCCESS";
export const TYPE_OF_BUSINESS_FAILURE = "TYPE_OF_BUSINESS_FAILURE";
