export const FETCH_DASHBOARD = "FETCH_DASHBOARD";
export const FETCH_DASHBOARD_SUCCESS = "FETCH_DASHBOARD_SUCCESS";
export const FETCH_DASHBOARD_FAIL = "FETCH_DASHBOARD_FAIL";

export const GET_CHECK_IN_DETAILED_LOG = "GET_CHECK_IN_DETAILED_LOG";
export const GET_CHECK_IN_DETAILED_LOG_SUCCESS = "GET_CHECK_IN_DETAILED_LOG_SUCCESS";
export const GET_CHECK_IN_DETAILED_LOG_FAIL = "GET_CHECK_IN_DETAILED_LOG_FAIL";

export const URL_CHECK_IN = "URL_CHECK_IN";
export const URL_CHECK_IN_SUCCESS = "URL_CHECK_IN_SUCCESS";
export const URL_CHECK_IN_FAIL = "URL_CHECK_IN_FAIL";

export const POST_DAILY_LOG = "POST_DAILY_LOG";
export const POST_DAILY_LOG_SUCCESS = "POST_DAILY_LOG_SUCCESS";
export const POST_DAILY_LOG_FAIL = "POST_DAILY_LOG_FAIL";

export const URL_DELETE_USER = "URL_DELETE_USER";
export const URL_DELETE_USER_SUCCESS = "URL_DELETE_USER_SUCCESS";
export const URL_DELETE_USER_FAIL = "URL_DELETE_USER_FAIL";

export const EDIT_PROFILE_PICTURE = "EDIT_PROFILE_PICTURE";
export const EDIT_PROFILE_PICTURE_SUCCESS = "EDIT_PROFILE_PICTURE_USER_SUCCESS";
export const EDIT_PROFILE_PICTURE_FAIL = "EDIT_PROFILE_PICTURE_FAIL";