export const RESET_REDUCER = "RESET_REDUCER";

export const CREATE_GROUP = 'CREATE_GROUP';

/**
 * Add salary Allowance
 */
export const ADD_SALARY_ALLOWANCE = "ADD_SALARY_ALLOWANCE";
export const ADD_SALARY_ALLOWANCE_SUCCESS = "ADD_SALARY_ALLOWANCE_SUCCESS";
export const ADD_SALARY_ALLOWANCE_FAILURE = "ADD_SALARY_ALLOWANCE_FAILURE";

/**
 * get Tax Sections
 */
export const GET_TAX_SECTIONS = "GET_TAX_SECTIONS";
export const GET_TAX_SECTIONS_SUCCESS = "GET_TAX_SECTIONS_SUCCESS";
export const GET_TAX_SECTIONS_FAILURE = "GET_TAX_SECTIONS_FAILURE";


/**
 * get Allowance Groups
 */
export const GET_ALLOWANCE_GROUPS = "GET_ALLOWANCE_GROUPS";
export const GET_ALLOWANCE_GROUPS_SUCCESS = "GET_ALLOWANCE_GROUPS_SUCCESS";
export const GET_ALLOWANCE_GROUPS_FAILURE = "GET_ALLOWANCE_GROUPS_FAILURE";

/**
 * get salary Allowance
 */
export const GET_SALARY_ALLOWANCE = "GET_SALARY_ALLOWANCE";
export const GET_SALARY_ALLOWANCE_SUCCESS = "GET_SALARY_ALLOWANCE_SUCCESS";
export const GET_SALARY_ALLOWANCE_FAILURE = "GET_SALARY_ALLOWANCE_FAILURE";

/**
 * add Allowance Group
 */
export const ADD_ALLOWANCE_GROUPS = "ADD_ALLOWANCE_GROUPS";
export const ADD_ALLOWANCE_GROUPS_SUCCESS = "ADD_ALLOWANCE_GROUPS_SUCCESS";
export const ADD_ALLOWANCE_GROUPS_FAILURE = "ADD_ALLOWANCE_GROUPS_FAILURE";


/**
 * add Employee Salary
 */
export const ADD_EMPLOYEE_SALARY = "ADD_EMPLOYEE_SALARY";
export const ADD_EMPLOYEE_SALARY_SUCCESS = "ADD_EMPLOYEE_SALARY_SUCCESS";
export const ADD_EMPLOYEE_SALARY_FAILURE = "ADD_EMPLOYEE_SALARY_FAILURE";


/**
 * get Employee Salary
 */

export const GET_EMPLOYEE_SALARY = "GET_EMPLOYEE_SALARY";
export const GET_EMPLOYEE_SALARY_SUCCESS = "GET_EMPLOYEE_SALARY_SUCCESS";
export const GET_EMPLOYEE_SALARY_FAILURE = "GET_EMPLOYEE_SALARY_FAILURE";
