export const RESET_REDUCER = "RESET_REDUCER";

export const CREATE_GROUP = 'CREATE_GROUP';

/**
 * Add company Allowance
 */
export const ADD_COMPANY_ALLOWANCE = "ADD_COMPANY_ALLOWANCE";
export const ADD_COMPANY_ALLOWANCE_SUCCESS = "ADD_COMPANY_ALLOWANCE_SUCCESS";
export const ADD_COMPANY_ALLOWANCE_FAILURE = "ADD_COMPANY_ALLOWANCE_FAILURE";

/**
 * Add company deduction
 */
export const ADD_COMPANY_DEDUCTION = "ADD_COMPANY_DEDUCTION";
export const ADD_COMPANY_DEDUCTION_SUCCESS = "ADD_COMPANY_DEDUCTION_SUCCESS";
export const ADD_COMPANY_DEDUCTION_FAILURE = "ADD_COMPANY_DEDUCTION_FAILURE";

/**
 * get Tax Sections
 */
export const GET_TAX_SECTIONS = "GET_TAX_SECTIONS";
export const GET_TAX_SECTIONS_SUCCESS = "GET_TAX_SECTIONS_SUCCESS";
export const GET_TAX_SECTIONS_FAILURE = "GET_TAX_SECTIONS_FAILURE";

/**
 * add Allowance Group
 */
export const ADD_ALLOWANCE_GROUPS = "ADD_ALLOWANCE_GROUPS";
export const ADD_ALLOWANCE_GROUPS_SUCCESS = "ADD_ALLOWANCE_GROUPS_SUCCESS";
export const ADD_ALLOWANCE_GROUPS_FAILURE = "ADD_ALLOWANCE_GROUPS_FAILURE";


/**
 * get Allowance Groups
 */
export const GET_ALLOWANCE_GROUPS = "GET_ALLOWANCE_GROUPS";
export const GET_ALLOWANCE_GROUPS_SUCCESS = "GET_ALLOWANCE_GROUPS_SUCCESS";
export const GET_ALLOWANCE_GROUPS_FAILURE = "GET_ALLOWANCE_GROUPS_FAILURE";

/**
 * get Allowance Group details
 */
export const GET_ALLOWANCE_GROUP_DETAILS = "GET_ALLOWANCE_GROUP_DETAILS";
export const GET_ALLOWANCE_GROUP_DETAILS_SUCCESS = "GET_ALLOWANCE_GROUP_DETAILS_SUCCESS";
export const GET_ALLOWANCE_GROUP_DETAILS_FAILURE = "GET_ALLOWANCE_GROUP_DETAILS_FAILURE";

/**
 * get salary Allowance
 */
export const GET_SALARY_ALLOWANCE = "GET_SALARY_ALLOWANCE";
export const GET_SALARY_ALLOWANCE_SUCCESS = "GET_SALARY_ALLOWANCE_SUCCESS";
export const GET_SALARY_ALLOWANCE_FAILURE = "GET_SALARY_ALLOWANCE_FAILURE";

/**
 * Get company allowance
 */
export const GET_COMPANY_ALLOWANCE = "GET_COMPANY_ALLOWANCE";
export const GET_COMPANY_ALLOWANCE_SUCCESS = "GET_COMPANY_ALLOWANCE_SUCCESS";
export const GET_COMPANY_ALLOWANCE_FAILURE = "GET_COMPANY_ALLOWANCE_FAILURE";

//setting selected allowance group item

export const SETTING_SELECTED_ALLOWANCE_GROUP_DETAILS = "SETTING_SELECTED_ALLOWANCE_GROUP_DETAILS"

//get company deductions

export const GET_COMPANY_DEDUCTIONS = "GET_COMPANY_DEDUCTIONS";
export const GET_COMPANY_DEDUCTIONS_SUCCESS = "GET_COMPANY_DEDUCTIONS_SUCCESS";
export const GET_COMPANY_DEDUCTIONS_FAILURE = "GET_COMPANY_DEDUCTIONS_FAILURE";

//setting selected deduction details

export const SETTING_SELECTED_DEDUCTION_DETAILS = "SETTING_SELECTED_DEDUCTION_DETAILS"


/**
 * add Employee Salary
 */
export const ADD_EMPLOYEE_SALARY = "ADD_EMPLOYEE_SALARY";
export const ADD_EMPLOYEE_SALARY_SUCCESS = "ADD_EMPLOYEE_SALARY_SUCCESS";
export const ADD_EMPLOYEE_SALARY_FAILURE = "ADD_EMPLOYEE_SALARY_FAILURE";


/**
 * get Employee Salary
 */

export const GET_EMPLOYEE_SALARY = "GET_EMPLOYEE_SALARY";
export const GET_EMPLOYEE_SALARY_SUCCESS = "GET_EMPLOYEE_SALARY_SUCCESS";
export const GET_EMPLOYEE_SALARY_FAILURE = "GET_EMPLOYEE_SALARY_FAILURE";
