export const Images = {
  Welcome: require('./images/Welcome/Welcome.png'),
  WelcomePattern: require('./images/WelcomePattern/WelcomePattern.png')
}
export const Icons = {
  Logo: require('./icons/Logo/Logo.png'),
  LogoSmall: require('./icons/LogoSmall/LogoSmall.png'),

  Admin: require('./icons/Admin/Admin.png'),
  Employee: require('./icons/Employee/Employee.png'),
  RegisterCompany: require('./icons/RegisterCompany/RegisterCompany.png'),
  Google: require('./icons/Google/Google.png'),
  Facebook: require('./icons/Facebook/Facebook.png'),
  Clients: require("./icons/Clients/Clients.png"),
  Department: require("./icons/Department/Department.png"),
  Projects: require("./icons/Projects/Projects.png"),
  TotalEmployee: require("./icons/TotalEmployee/TotalEmployee.png"),
  EmployeePortfolio: require('./icons/EmployeePortfolio/EmployeePortfolio.png'),
  LocationPortfolio: require('./icons/LocationPortfolio/LocationPortfolio.png'),
  HolidayCalendar: require('./icons/HolidayCalendar/HolidayCalendar.png'),
  Report: require('./icons/Report/Report.png'),
  Dashboard: require('./icons/Dashboard/Dashboard.png'),
  UPLOADFILES: require('./icons/UploadFiles/UploadFiles.png'),
  Search: require('./icons/Search/Search.png'),
  Calendar: require('./icons/Calendar/Calendar.png'),
  Download: require('./icons/DownLoad/Download.png'),
  Edit: require('./icons/Edit/Edit.png'),
  Gallery: require('./icons/Gallery/Gallery.png'),
  Delete: require('./icons/Delete/Delete.png'),
  Eye: require('./icons/Eye/Eye.png'),
  Group1: require('./icons/Group1/Group1.png'),
  Group2: require('./icons/Group2/Group2.png'),
  Attendance: require('./icons/Attendance/Attendance.png'),
  Dailystats: require('./icons/DailyStats/DailyStats.png'),
  Leave: require('./icons/Leave/Leave.png'),
  Timesheets: require('./icons/TimeSheets/TimeSheets.png'),
  EDocuments: require('./icons/E-Document/EDocument.png'),
  Notifications: require('./icons/Notifications/Notifications.png'),
  SalaryCalculations: require('./icons/SalaryCalculations/SalaryCalculations.png'),
  ReportWeb: require('./icons/Report/Report.png'),
  Salarypayments: require('./icons/SalaryPayments/Salarypayments.png'),
  Pettycash: require('./icons/PettyCash/PettyCash.png'),
  PaySlips: require('./icons/PaySlips/PaySlips.png'),
  Location: require('./icons/Location/Location.png'),
  Instagram: require('./icons/Instagram/Instagram.png'),
  FacebookWeb: require('./icons/Facebook-Website/Facebook.png'),
  Twitter: require('./icons/Twitter/Twitter.png'),
  Mail: require('./icons/Mail/Mail.png'),
  Mobile: require('./icons/Mobile/Mobile.png'),
  Linkedin: require('./icons/Linkedin/Linkedin.png'),
  Zenylog: require('./icons/Zenylog/Zenylog.png'),
  ProfilePlaceHolder: require('./icons/ProfilePlaceHolder/ProfilePlaceHolder.png'),
  TickActive: require('./icons/TickActive/TickActive.png'),
  TickDefault: require('./icons/TickDefault/TickDefault.png'),
}


